Added tools, some untested

diff --git a/scripts/tools/bashescal b/scripts/tools/bashescal
--- a/scripts/tools/bashescal
+++ b/scripts/tools/bashescal
@@ -1,16 +1,30 @@
 #!/usr/bin/env bash
+# ____           _____ _    _ ______  _____  _____          _ 
+#|  _ \   /\    / ____| |  | |  ____|/ ____|/ ____|   /\   | |      AUTHOR:  Decator
+#| |_) | /  \  | (___ | |__| | |__  | (___ | |       /  \  | |      WEBSITE: https://el-wumbus.github.io/
+#|  _ < / /\ \  \___ \|  __  |  __|  \___ \| |      / /\ \ | |      DISCORD: https://discord.gg/8wBUFeGGYc
+#| |_) / ____ \ ____) | |  | | |____ ____) | |____ / ____ \| |____  GITHUB:  https://github.com/El-Wumbus
+#|____/_/    \_\_____/|_|  |_|______|_____/ \_____/_/    \_\______|
+# NAME: bashescal
+# DESCRIPTION: changes the privilege escalation tool in the bashrc when using the variable $privE,
+# this is done in my(decator) configs
+# verison 0.1.0 TESTING
 
 if [ "$1" == "" ]; then
     printf "Usage: bashescal <argument> e.g. 'bashescal doas'"; exit 1
 fi
 
 if [ "$privE" == "$1" ]; then
-    printf "The privilege escalation tool is already set to %s", "$1"
+    printf "The \$privE is already set to %s", "$1"
 else
     lineNum=$(grep -n 'export privE=' $HOME/.bashrc | awk -F ':' '{print $1}') # Returns the line that 'export privE=' is found
-    if [ "$lineNum" == "" ] || [ $lineNum -lt 1 ]; then
-        exit 1
+    if [ "$lineNum" == "" ]; then
+        echo "export privE='$1'" >> $HOME/.bashrc # If the variable declaration isnt found in in the bashrc then it will append the line and exit.
+        exit 0
+    elif [ $lineNum -lt 1 ]; then 
+    printf "Line Number Cannot be less than one" exit 1
     fi
+
     sed -i "${lineNum}s/.*/privE=\"${1}\"/" "$HOME/.bashrc" # Replace the line that the 'privE' variable is defined
     source $HOME/.bashrc
 fi
diff --git a/scripts/tools/extract b/scripts/tools/extract
--- a/scripts/tools/extract
+++ b/scripts/tools/extract
@@ -1,9 +1,26 @@
 #! /usr/bin/env bash
 cpIso() {
-  mkdir /tmp/image
-  sudo mount  $1 /tmp/image -o ro,loop -t iso9660
-  cp /tmp/image/* ./image
-  sudo umount /tmp/image
+  printf "Notice: An Iso cannot be decompressed, it will be mounted, copied, then unmounted.\n For this sudo is used."
+  file="$1"
+  dirName="$(printf '$file' | awk -F '.' '{print $1}' )"
+  sudo mkdir /tmp/${dirname}
+  sudo mount  $1 /tmp/${dirname} -o ro,loop -t iso9660 || sudo rmdir /tmp/${dirname} && echo "ISO failed to mount. Cannot extract files using extract." && exit
+  sudo cp -rv /tmp/${dirname}/* ./${dirname}
+  sudo umount /tmp/${dirname}
+  rmdir /tmp/${dirname}
+  sudo chown $USER ./${dirname}
+  echo "files have been transferred to ./${dirName}"
+}
+
+cpDmg() {
+  find /lib/modules -name "hfs*.ko" || printf "hfs kernel modules not found, cannot continue." && exit 1
+  file="$1"
+  dirName="$(printf "$file" | awk -F '.' '{print $1}' )"
+  sudo mkdir /tmp/${dirname}
+  sudo mount -t hfsplus $1 /tmp/${dirname} || sudo rmdir /tmp/${dirname} && printf "File '$1' is either unsupported or compressed. Cannot extract files using extract. \nTry using 'dmg2img'." && exit 1
+  sudo cp -rv /tmp/${dirname}/* ./${dirname}
+  sudo umount /tmp/${dirname}
+  sudo chown $USER ./${dirname}
 }
 
 if [ -f "$1" ] ; then
@@ -25,9 +42,11 @@ if [ -f "$1" ] ; then
     *.xz)        xz -d $1      ;;
     *.shar)      unshar $1     ;;
     *.iso)       cpIso         ;;
+    version)  echo "version 1.0.1";;
     *)           echo -e "'$1' cannot be extracted via extract. please do so manually.\n" ;;
   esac
 else
   echo -e "'$1' is not a valid file \n"
 fi
 
+exit 0
